FROM node:18 AS build

WORKDIR /app

ENV PATH="/app/node_modules/.bin:$PATH"

# Install dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Build
COPY src ./src
COPY public ./public
COPY .eslintrc.js ./
COPY tsconfig.json ./
COPY webpack.config.js ./
RUN npm run build

# Nginx stage
FROM nginx:stable-alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80